signin:
  passphrase: make jar not war

domain:
  microservice:
    username: user
    password: springworkshop

spring:
  sleuth:
    sampler:
      percentage: 1.0

hystrix:
  command:
    StudentDomainClient#loadStudent(String):
      circuitBreaker:
        requestVolumeThreshold: 5
